<a href="https://colab.research.google.com/github/mimern/data-science-bootcamp/blob/main/DataScinceBootCapmp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Numpy

In [1]:
import numpy as np

In [ ]:
dir(np)

In [11]:
x = np.array([[2,3,3], [-3,1,2]])
print(x.ndim)
print(x.shape)
x

2
(2, 3)


array([[ 2,  3,  3],
       [-3,  1,  2]])

3D

In [12]:
x = np.array(
    [[[4,3,1],
      [3,1,2]],
     
     [[3,4,5],
      [5,6,7]],
     [[7,8,2],
      [4,5,6]]]
)

In [16]:
######################################################

3

In [18]:
A = np.array([1,2,3], dtype='float')

A.dtype


dtype('float64')

In [ ]:
A = np.array([1,2,3], dtype='float')

A.dtype

In [19]:
np.full(shape=(4,4), fill_value=3.14, dtype='float')

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [20]:
np.arange(100,0,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [22]:
list(range(100,0,-10))

[100, 90, 80, 70, 60, 50, 40, 30, 20, 10]

In [24]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [28]:
A = np.arange(16)
A.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#### operacje

In [38]:
A = np.array([[3,1],[4,2]])
B = np.array([[3,-1],[3,2]])

In [35]:
# +, -, *, /

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [40]:
A*B

array([[ 9, -1],
       [12,  4]])

In [41]:
 ### np.dot - mnozenie macierzowe lub @ lub A.dot(B)
 np.dot(A,B)

array([[12, -1],
       [18,  0]])

In [44]:
A.dot(B)

array([[12, -1],
       [18,  0]])

In [45]:
A@B

array([[12, -1],
       [18,  0]])

In [56]:
np.random.seed(0)  # siejemy ziarno losowe xd
X = np.random.randn(10,4) ### z rozkladu normalnego
X

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385],
       [ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275]])

In [59]:
X = np.random.rand(10,4) ### z rozkladu jednostajnego
X

array([[0.31542835, 0.36371077, 0.57019677, 0.43860151],
       [0.98837384, 0.10204481, 0.20887676, 0.16130952],
       [0.65310833, 0.2532916 , 0.46631077, 0.24442559],
       [0.15896958, 0.11037514, 0.65632959, 0.13818295],
       [0.19658236, 0.36872517, 0.82099323, 0.09710128],
       [0.83794491, 0.09609841, 0.97645947, 0.4686512 ],
       [0.97676109, 0.60484552, 0.73926358, 0.03918779],
       [0.28280696, 0.12019656, 0.2961402 , 0.11872772],
       [0.31798318, 0.41426299, 0.0641475 , 0.69247212],
       [0.56660145, 0.26538949, 0.52324805, 0.09394051]])

In [61]:
np.random.randint(low=10,high=101, size=10)

array([75, 46, 20, 96, 53, 21, 12, 61, 90, 42])

In [63]:
B = np.arange(0,1,0.05)

np.random.choice(B)

0.30000000000000004

In [ ]:
###############################################################################################################33

In [65]:
np.all([2,3,0])

False

In [68]:
np.any([0,2,0])

True

In [74]:
a =0
b =1

In [75]:
a = bool(a)
b = bool(b)

print(a)
print(b)

False
True


In [81]:
R = np.random.rand(5)
R

array([0.67781654, 0.27000797, 0.73519402, 0.96218855, 0.24875314])

In [82]:
np.argsort(R) ###sortuje indexy

array([4, 1, 0, 2, 3])

In [86]:
### slicey
R[[0,2]]
R[np.argsort(R)[0:2]]

array([0.24875314, 0.27000797])

In [95]:
### slce wielowymiary

A = np.random.randint(10,20, size=(4,5))
A

array([[15, 15, 10, 18, 11],
       [11, 10, 13, 18, 18],
       [14, 14, 10, 19, 13],
       [17, 13, 12, 11, 11]])

In [107]:
A[0] # indexowanie po wierszach
A[:,0]  ## indexowanie po kolumnach

17

In [118]:
A[1:3,1:3] ## slice

array([[10, 13],
       [14, 10]])

In [120]:
A[1,2] = 0
A

array([[15, 15, 10, 18, 11],
       [11, 10,  0, 18, 18],
       [14, 14, 10, 19, 13],
       [17, 13, 12, 11, 11]])

In [124]:
### iteracja + maski

for r in A:
  print(r[0])

15
11
14
17


In [ ]:
for item in A.flat:     ### po kazdym elemencie
  print(item)

In [126]:
A.shape

(4, 5)

In [127]:
A.ravel()   ### spłaszczamy dane

array([15, 15, 10, 18, 11, 11, 10,  0, 18, 18, 14, 14, 10, 19, 13, 17, 13,
       12, 11, 11])

In [128]:
A.T    # transponowanie macierzy - to znam 

array([[15, 11, 14, 17],
       [15, 10, 14, 13],
       [10,  0, 10, 12],
       [18, 18, 19, 11],
       [11, 18, 13, 11]])

In [ ]:
#### MASKI LOGICZNE

In [131]:
A = np.arange(-10,10,0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [132]:
A > 0  # -> tj maska logiczna

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [135]:
# wycinanie za pomoca maski logicznej
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [138]:
np.bitwise_and(A>-5, A<5)   # jak mamy and ( z or to bitwise_or) tworzymy maske

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [139]:
A[np.bitwise_and(A>-5, A<5)] # wycinamy

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])